### ISSUE TITLE
Unneeded code bit

### ISSUE THREAD

**Issue by RamezIssac** [nunombispo/slick_reporting_article#1]
Hello There !
Thank you so much for the article on Demistifying Slick Reporting .

I wanted to communicate 2 things

1. 
https://github.com/nunombispo/slick_reporting_article/blob/ed614d4c6c6cfe59b07f7f92c769520fd8654c27/sales_app/views.py#L11
This bit of code is not needed and have no effect .

2. For more demystifying, i have update the demo site [django-slick-reporting.com](https://django-slick-reporting.com).
Hope you find it useful.

Kind regards

**Comment by nunombispo** [comment]
Hi there,

Thank you for much for your feedback, and thank you for a great package.

The [django-slick-reporting.com](https://django-slick-reporting.com/) was not working when I was researching for the article, so also thank you for updating it.

I have updated the article to reflect your feedback.

Best regards.
